"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import osprey.rpc.common.v1.execution_result_pb2
import osprey.rpc.common.v1.verdicts_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ExecutionMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ExecutionModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ExecutionMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EXECUTION_MODE_UNSPECIFIED: _ExecutionMode.ValueType  # 0
    EXECUTION_MODE_SYNC: _ExecutionMode.ValueType  # 1
    EXECUTION_MODE_ASYNC: _ExecutionMode.ValueType  # 2

class ExecutionMode(_ExecutionMode, metaclass=_ExecutionModeEnumTypeWrapper):
    """Execution mode tells the worker which latency tier an action originated from.
    MODE_UNSPECIFIED means the producer is an older binary that doesn't stamp mode;
    the worker treats it as "no tier filtering" for backward compatibility.
    """

EXECUTION_MODE_UNSPECIFIED: ExecutionMode.ValueType  # 0
EXECUTION_MODE_SYNC: ExecutionMode.ValueType  # 1
EXECUTION_MODE_ASYNC: ExecutionMode.ValueType  # 2
global___ExecutionMode = ExecutionMode

@typing.final
class OspreyCoordinatorAction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_ID_FIELD_NUMBER: builtins.int
    ACTION_ID_FIELD_NUMBER: builtins.int
    ACTION_NAME_FIELD_NUMBER: builtins.int
    JSON_ACTION_DATA_FIELD_NUMBER: builtins.int
    PROTO_ACTION_DATA_FIELD_NUMBER: builtins.int
    JSON_SECRET_DATA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    ack_id: builtins.int
    action_id: builtins.int
    action_name: builtins.str
    json_action_data: builtins.bytes
    proto_action_data: builtins.bytes
    json_secret_data: builtins.bytes
    """this will soon be replaced by proto refactors"""
    mode: global___ExecutionMode.ValueType
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        ack_id: builtins.int = ...,
        action_id: builtins.int = ...,
        action_name: builtins.str = ...,
        json_action_data: builtins.bytes = ...,
        proto_action_data: builtins.bytes = ...,
        json_secret_data: builtins.bytes = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        mode: global___ExecutionMode.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["action_data", b"action_data", "json_action_data", b"json_action_data", "json_secret_data", b"json_secret_data", "proto_action_data", b"proto_action_data", "secret_data", b"secret_data", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ack_id", b"ack_id", "action_data", b"action_data", "action_id", b"action_id", "action_name", b"action_name", "json_action_data", b"json_action_data", "json_secret_data", b"json_secret_data", "mode", b"mode", "proto_action_data", b"proto_action_data", "secret_data", b"secret_data", "timestamp", b"timestamp"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["action_data", b"action_data"]) -> typing.Literal["json_action_data", "proto_action_data"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["secret_data", b"secret_data"]) -> typing.Literal["json_secret_data"] | None: ...

global___OspreyCoordinatorAction = OspreyCoordinatorAction

@typing.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_REQUEST_FIELD_NUMBER: builtins.int
    DISCONNECT_FIELD_NUMBER: builtins.int
    @property
    def action_request(self) -> global___ActionRequest: ...
    @property
    def disconnect(self) -> global___Disconnect: ...
    def __init__(
        self,
        *,
        action_request: global___ActionRequest | None = ...,
        disconnect: global___Disconnect | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["action_request", b"action_request", "disconnect", b"disconnect", "request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["action_request", b"action_request", "disconnect", b"disconnect", "request", b"request"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["request", b"request"]) -> typing.Literal["action_request", "disconnect"] | None: ...

global___Request = Request

@typing.final
class ClientDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    MAX_UNACKED_FIELD_NUMBER: builtins.int
    id: builtins.str
    max_unacked: builtins.int
    """Maximum number of un-acked actions per stream. The coordinator will dispatch
    up to this many actions before requiring an ack. Default 0 → treated as 1
    (today's strict-serial behavior). Raising this lifts per-stream throughput
    for slow async UDFs; see osprey_async_worker docs.
    """
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        max_unacked: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "max_unacked", b"max_unacked"]) -> None: ...

global___ClientDetails = ClientDetails

@typing.final
class Disconnect(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_OR_NACK_FIELD_NUMBER: builtins.int
    @property
    def ack_or_nack(self) -> global___AckOrNack: ...
    def __init__(
        self,
        *,
        ack_or_nack: global___AckOrNack | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ack_or_nack", b"ack_or_nack"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ack_or_nack", b"ack_or_nack"]) -> None: ...

global___Disconnect = Disconnect

@typing.final
class ActionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIAL_FIELD_NUMBER: builtins.int
    ACK_OR_NACK_FIELD_NUMBER: builtins.int
    @property
    def initial(self) -> global___ClientDetails: ...
    @property
    def ack_or_nack(self) -> global___AckOrNack: ...
    def __init__(
        self,
        *,
        initial: global___ClientDetails | None = ...,
        ack_or_nack: global___AckOrNack | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ack_or_nack", b"ack_or_nack", "action_request", b"action_request", "initial", b"initial"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ack_or_nack", b"ack_or_nack", "action_request", b"action_request", "initial", b"initial"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["action_request", b"action_request"]) -> typing.Literal["initial", "ack_or_nack"] | None: ...

global___ActionRequest = ActionRequest

@typing.final
class Ack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_RESULT_FIELD_NUMBER: builtins.int
    VERDICTS_FIELD_NUMBER: builtins.int
    @property
    def execution_result(self) -> osprey.rpc.common.v1.execution_result_pb2.ExecutionResult: ...
    @property
    def verdicts(self) -> osprey.rpc.common.v1.verdicts_pb2.Verdicts: ...
    def __init__(
        self,
        *,
        execution_result: osprey.rpc.common.v1.execution_result_pb2.ExecutionResult | None = ...,
        verdicts: osprey.rpc.common.v1.verdicts_pb2.Verdicts | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["execution_result", b"execution_result", "verdicts", b"verdicts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execution_result", b"execution_result", "verdicts", b"verdicts"]) -> None: ...

global___Ack = Ack

@typing.final
class Nack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Nack = Nack

@typing.final
class AckOrNack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_ID_FIELD_NUMBER: builtins.int
    ACK_FIELD_NUMBER: builtins.int
    NACK_FIELD_NUMBER: builtins.int
    ack_id: builtins.int
    @property
    def ack(self) -> global___Ack: ...
    @property
    def nack(self) -> global___Nack: ...
    def __init__(
        self,
        *,
        ack_id: builtins.int = ...,
        ack: global___Ack | None = ...,
        nack: global___Nack | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ack", b"ack", "ack_or_nack", b"ack_or_nack", "nack", b"nack"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ack", b"ack", "ack_id", b"ack_id", "ack_or_nack", b"ack_or_nack", "nack", b"nack"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["ack_or_nack", b"ack_or_nack"]) -> typing.Literal["ack", "nack"] | None: ...

global___AckOrNack = AckOrNack
